name: dependent-lamb
version: '0.0.1'
synopsis: An implementation of (Graded Modal Dependent Type Theory)
author: Ben Moon, Dominic Orchard
copyright: 2020 authors
license: BSD3
dependencies:
- base >=4.10 && <5

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-type-defaults
- -XOverloadedStrings

library:
  source-dirs: src
  build-tools:
   - alex
   - happy
  dependencies:
   - containers
   - mtl
   - pretty
   - transformers
   - array
   - clock
   - extra
   - sbv >= 8.6
  exposed-modules:
   - Language.Dlam.Interpreter
   - Language.Dlam.Substitution
   - Language.Dlam.Syntax.Concrete
   - Language.Dlam.Syntax.Parser
   - Language.Dlam.Types
   - Language.Dlam.TypeChecking.Monad
   - Language.Dlam.Util.Pretty
  other-modules:
   - Language.Dlam.Syntax.Abstract
   - Language.Dlam.Syntax.Common
   - Language.Dlam.Syntax.Common.Language
   - Language.Dlam.Syntax.Concrete.Name
   - Language.Dlam.Syntax.Free
   - Language.Dlam.Syntax.Internal
   - Language.Dlam.Syntax.Lexer
   - Language.Dlam.Syntax.Literal
   - Language.Dlam.Syntax.Parser.Alex
   - Language.Dlam.Syntax.Parser.Comments
   - Language.Dlam.Syntax.Parser.Layout
   - Language.Dlam.Syntax.Parser.LexActions
   - Language.Dlam.Syntax.Parser.LookAhead
   - Language.Dlam.Syntax.Parser.Monad
   - Language.Dlam.Syntax.Parser.Tokens
   - Language.Dlam.Syntax.Position
   - Language.Dlam.Syntax.Translation.ConcreteToAbstract
   - Language.Dlam.Scoping.Monad
   - Language.Dlam.Scoping.Monad.Base
   - Language.Dlam.Scoping.Monad.Exception
   - Language.Dlam.Scoping.Scope
   - Language.Dlam.TypeChecking.Monad.Base
   - Language.Dlam.TypeChecking.Monad.Exception
   - Language.Dlam.TypeChecking.Monad.Grading
   - Language.Dlam.TypeChecking.Monad.Solver
   - Language.Dlam.TypeChecking.Constraints
   - Language.Dlam.TypeChecking.Constraints.SNatX
   - Language.Dlam.TypeChecking.Constraints.SymbolicGrades
   - Language.Dlam.TypeChecking.Predicates
   - Language.Dlam.TypeChecking.Solver.Monad
   - Language.Dlam.Util.Lens
   - Language.Dlam.Util.Peekaboo

executables:
  gerty:
    main: Main.hs
    ghc-options: -main-is Dlam
    dependencies:
     - dependent-lamb
     - directory
     - clock

tests:
  dependent-lamb:
    main: Test.hs
    source-dirs: tests
    dependencies:
    - dependent-lamb
    - directory
    - strict
    - tasty
    - tasty-golden
    - tasty-hunit
