name: dependent-lamb
version: '0.0.1'
synopsis: Minimal, dependently-typed programming language
author: Ben Moon
copyright: 2020 authors
license: BSD3
dependencies:
- base >=4.10 && <5

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-type-defaults

library:
  source-dirs: src
  build-tools:
   - alex
   - happy
  dependencies:
   - containers
   - mtl
   - pretty
   - transformers
   - array
   - text
  exposed-modules:
   - Language.Dlam.Interpreter
   - Language.Dlam.Substitution
   - Language.Dlam.Syntax.Concrete
   - Language.Dlam.Syntax.Parser
   - Language.Dlam.Types
   - Language.Dlam.TypeChecking.Monad
  other-modules:
   - Language.Dlam.FirstParameter
   - Language.Dlam.Syntax.Concrete.Name
   - Language.Dlam.Syntax.Free
   - Language.Dlam.Syntax.Lexer
   - Language.Dlam.TypeChecking.Monad.Base
   - Language.Dlam.Util.Pretty

executables:
  dlam:
    main: Main.hs
    ghc-options: -main-is Dlam
    dependencies:
     - dependent-lamb
     - directory

tests:
  dependent-lamb:
    main: Test.hs
    source-dirs: tests
    dependencies:
    - dependent-lamb
    - strict
    - tasty
    - tasty-golden
    - tasty-hunit
