name: dependent-lamb
version: '0.0.1'
synopsis: Minimal, dependently-typed programming language
author: Ben Moon
copyright: 2020 authors
license: BSD3
dependencies:
- base >=4.10 && <5

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-type-defaults

library:
  source-dirs: src
  build-tools:
   - alex
   - happy
  dependencies:
   - containers
   - transformers
   - array
   - text
  exposed-modules:
   - Language.Dlam.Binders
   - Language.Dlam.Parser
   - Language.Dlam.PrettyPrint
   - Language.Dlam.Substitution
   - Language.Dlam.Syntax
   - Language.Dlam.Types
  other-modules:
   - Language.Dlam.FirstParameter
   - Language.Dlam.Lexer
   - Language.Dlam.Options

executables:
  dlam:
    main: Main.hs
    ghc-options: -main-is Dlam
    dependencies:
     - dependent-lamb
     - containers
     - directory
     - mtl
     - transformers
